# Generated by Django 4.2.7 on 2025-04-14 16:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoundVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('license_plate', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('reported_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('condition', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('reporter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reporter_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched')], default='pending', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LostVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('license_plate', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('reported_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_location', models.CharField(max_length=255)),
                ('last_seen_date', models.DateField()),
                ('last_seen_time', models.TimeField(blank=True, null=True)),
                ('circumstances', models.TextField(blank=True, null=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_email', models.EmailField(max_length=254)),
                ('owner_phone', models.CharField(max_length=20)),
                ('alt_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('searching', 'Searching'), ('found', 'Found')], default='searching', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notification_sent', models.BooleanField(default=False)),
                ('found_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.foundvehicle')),
                ('lost_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.lostvehicle')),
            ],
        ),
    ]
